/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as WorkElvashHardwareRouteImport } from './routes/work.elvash-hardware'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkElvashHardwareRoute = WorkElvashHardwareRouteImport.update({
  id: '/work/elvash-hardware',
  path: '/work/elvash-hardware',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/work/elvash-hardware': typeof WorkElvashHardwareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/work/elvash-hardware': typeof WorkElvashHardwareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/work/elvash-hardware': typeof WorkElvashHardwareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/analytics' | '/work/elvash-hardware'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/analytics' | '/work/elvash-hardware'
  id: '__root__' | '/' | '/admin/analytics' | '/work/elvash-hardware'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  WorkElvashHardwareRoute: typeof WorkElvashHardwareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/elvash-hardware': {
      id: '/work/elvash-hardware'
      path: '/work/elvash-hardware'
      fullPath: '/work/elvash-hardware'
      preLoaderRoute: typeof WorkElvashHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  WorkElvashHardwareRoute: WorkElvashHardwareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
